#!/bin/sh

if [ $# -le 1 ]; then
	echo usage:
	echo crop_pdf2jpg image1.pdf \[ image2.pdf ... \]
	exit -1
fi

while [ $# -gt 0 ]; do
	f=$1 ;
	convert -quality 90 -density 128 \
		-crop 640x480+0+80 "$f" "${f%.pdf}.jpg" ;
	shift ;
done


