#!/bin/sh

FILE=$1
OUT=${FILE%.gp}.eps

TIME=$(head -1 ${FILE}|tail -1|LC_ALL=C awk '{print $2}'|\
	perl -e 'while(<>){printf("%g\n",$_);}');
TITLE="t=$TIME"

gnuplot - << END
set output '$OUT'
set terminal post color
set palette rgbformulae 30,31,32 negative
set title '$TITLE'
unset key

set multiplot

set surface
unset contour
set view map
set pm3d interpolate 2,2
set cbrange [0:0.5]
splot [0:1][0:0.5] '$FILE' u 1:2:(\$8>=0?\$5/\$3:1/0) with pm3d 

unset surface
set cntrparam levels discrete 0.0
set contour base
set style line 99 linetype 1 linecolor 0 linewidth 3
splot [0:1][0:0.5] '$FILE' u 1:2:8 w l ls 99

unset multiplot
END

